modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="ezstorage"
version="1.0.0"
displayName="EZStorage 2"
description='''Storage: Simplified again.'''
authors="scuba10steve, zerofall, SBlectric"

[[dependencies.ezstorage]]
modId="neoforge"
type="required"
versionRange="[21.1,22)"
ordering="NONE"
side="BOTH"

[[dependencies.ezstorage]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
