modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="s3"
version="${mod_version}"
displayName="Steve's Simple Storage"
description='''Massive, scalable storage for Minecraft.'''
authors="scuba10steve, zerofall, SBlectric"

[[dependencies.s3]]
modId="neoforge"
type="required"
versionRange="[21.1,22)"
ordering="NONE"
side="BOTH"

[[dependencies.s3]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
